import type { DownloadTrackType } from "./types";

export function useFetchDownloads():DownloadTrackType[]{

    return [
        {
        id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/arashghomeishi/inxmgbs90hpq",
            "name": "چه کنم - عرفان طهماسبی",
            "artist_name": "Pianist | Musicaholic",
            "album": null,
            "duration": 142140,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-6ASEDRy2X8M2cAlI-plKQbA-large.jpg",
            "id": 1,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/25band/hamishe-ba-hamim",
            "name": "Hamishe Ba Hamim همیشه با همیم",
            "artist_name": "25Band",
            "album": null,
            "duration": 267310,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000054432011-tc24td-large.jpg",
            "id": 2,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/djmaay/dj-maay-mifa-road-02",
            "name": "Dj Maay - Mifa Road 02",
            "artist_name": "Dj Maay",
            "album": null,
            "duration": 1476461,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-OxYoNLmpM7XbL5Ql-ZSNISQ-large.jpg",
            "id": 3,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/arashghomeishi/9pg06mwtbzpj",
            "name": "مو براش دریا شدم - عرفان طهماسبی",
            "artist_name": "Pianist | Musicaholic",
            "album": null,
            "duration": 198975,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-hd0Ix5VPzV4gYEaM-XH7RmQ-large.jpg",
            "id": 4,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/talebli/daste-man-nist",
            "name": "Shadmehr Aghili -Daste Man Nist",
            "artist_name": "Hadi Talebli",
            "album": null,
            "duration": 218848,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-qiFPysPvwkOQn1d5-R81aDQ-large.jpg",
            "id": 5,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/user-289523664/reza-malekzadeh-aram-aram",
            "name": "نشد برای عشقمان برای این دیوانه ات سفر کنی ... آرام آرام رضا ملک زاده",
            "artist_name": "",
            "album": null,
            "duration": 201404,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-gl6qPRkCbc1j5y7b-gB5oHQ-large.jpg",
            "id": 6,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/samiloww/del",
            "name": "Sami Low, Raha & The Don - Del | OFFICIAL TRACK",
            "artist_name": "Sami Low",
            "album": null,
            "duration": 180254,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-jiqVONlOjIl0RMx6-FMaPhA-large.jpg",
            "id": 7,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/tudo-loca/ghawgha-taban-meboosamat",
            "name": "Ghawgha Taban Meboosamat",
            "artist_name": "Loca Tudo",
            "album": null,
            "duration": 157297,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000490896039-oyj9qb-large.jpg",
            "id": 8,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/25band/az-pisham-miri",
            "name": "Az Pisham Miri از پیشم میری",
            "artist_name": "25Band",
            "album": null,
            "duration": 238074,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000080356822-21qzxk-large.jpg",
            "id": 9,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/armin-mahdiani/parastoo-ahmadi-aziz-joon",
            "name": "parastoo ahmadi - aziz joon",
            "artist_name": "",
            "album": null,
            "duration": 233770,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000656415004-ewgzup-large.jpg",
            "id": 10,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/studio13studio13/rafto-gozasht",
            "name": "Rafto Gozasht",
            "artist_name": "",
            "album": null,
            "duration": 200153,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000522293178-03i97y-large.jpg",
            "id": 11,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/shahr-zad/kurdish-lullaby",
            "name": "لالایی کُردی | Kurdish Lullaby",
            "artist_name": "Shahrzad Beheshtian",
            "album": null,
            "duration": 129945,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000061796407-wryrtj-large.jpg",
            "id": 12,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/shivaaaz/firnjxk4lty4",
            "name": "سوگند | تو بخوان (کاور آهنگ مرضیه)",
            "artist_name": "",
            "album": null,
            "duration": 139833,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-n1sbHTxB8yzQKljI-wBa30A-large.jpg",
            "id": 13,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/h_star/octave-be-in-chiza-nist-ft-hana",
            "name": "Octave - Be In Chiza Nist (Ft Hana)",
            "artist_name": "",
            "album": null,
            "duration": 273417,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-vdW4Fh3yx7zBK7mm-r7AQXA-large.jpg",
            "id": 14,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/arsalanmusic/arsalan-az-khodet-bepors",
            "name": "Az Khodet Bepors | ارسلان - از خودت بپرس",
            "artist_name": "",
            "album": null,
            "duration": 188998,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000170762339-jsnxp0-large.jpg",
            "id": 15,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/musickhane/najva-khabazian-labkhand",
            "name": "Najva Khabazian - Labkhand | نجوا خبازیان - لبخند",
            "artist_name": "موزیکخانه",
            "album": null,
            "duration": 210862,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000507163338-a1k27e-large.jpg",
            "id": 16,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/chaartmusic/paykoob-band-mimiram",
            "name": "Paykoob Band - Mimiram",
            "artist_name": "Chaart Music",
            "album": null,
            "duration": 204334,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-DwLlwgUKVULQnlO0-xAar3A-large.jpg",
            "id": 17,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/25band/bia-bia",
            "name": "Bia Bia بیا بیا",
            "artist_name": "25Band",
            "album": null,
            "duration": 181698,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000009919342-dhbk4l-large.jpg",
            "id": 18,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/minorammusic/cheshmat",
            "name": "cheshmat",
            "artist_name": "",
            "album": null,
            "duration": 191748,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-l7UcFA89zRjGlGOh-LY7JJw-large.jpg",
            "id": 19,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/abdi-behravanfar/dovel",
            "name": "Do vel (version 1) دو وِل",
            "artist_name": "Abdi Behravanfar",
            "album": null,
            "duration": 401957,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000219338338-vflrvs-large.jpg",
            "id": 20,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/user-171332951/shervin-bimeye-omr-mp3",
            "name": "Shervin - Bimeye Omr.mp3",
            "artist_name": "",
            "album": null,
            "duration": 201110,
            "is_synced": false,
            "thumbnail": null,
            "id": 21,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/shahr-zad/govah",
            "name": "گُواه",
            "artist_name": "Shahrzad Beheshtian",
            "album": null,
            "duration": 311556,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000668049106-cjkcfl-large.jpg",
            "id": 22,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/hossein-azarakhshi-1/100-1",
            "name": "باران - 100 بار",
            "artist_name": "Hossein Azarakhshi",
            "album": null,
            "duration": 222949,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000066269685-fdg1oa-large.jpg",
            "id": 23,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/shantia-karami-234607140/movazebam-bash",
            "name": "Movazebam Bash:)",
            "artist_name": "shantia karami",
            "album": null,
            "duration": 214929,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-BIQb2VwHEdSsFC1f-lyt4xQ-large.jpg",
            "id": 24,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/sormeh_trio/elegy",
            "name": "ELEGY(sormeh)",
            "artist_name": "Sormeh Music",
            "album": null,
            "duration": 379919,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000013255666-2qc0qz-large.jpg",
            "id": 25,
        }
        },
        {id:1,
        status:'downloading',
        track:{
            "url": "https://soundcloud.com/25band/peurto-rico-e",
            "name": "Peurto Rico (e) پورتو ریکو",
            "artist_name": "25Band",
            "album": null,
            "duration": 219997,
            "is_synced": false,
            "thumbnail": "https://i1.sndcdn.com/artworks-000016518555-3tat68-large.jpg",
            "id": 26,
        }
        },
    ]
}